//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by LDtkToUnity
//     from Assets/LDtk/LDtkVaniaSample.ldtk
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDtkLevelManagerSample
{
    /// <summary>
    /// LDtk Enum for LDtkVaniaSample
    /// </summary>
    public enum LDtkLevelManagerAreas
    {
        Factory,
        Mall,
        World_2_Area
    }
}