//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by LDtkToUnity
//     from Assets/LDtk/LDtkVaniaSample.ldtk
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poputara.LDtk
{
    /// <summary>
    /// LDtk Enum for LDtkEnums
    /// </summary>
    public enum GlobalTransitionsTarget
    {
        Lights
    }

    /// <summary>
    /// LDtk Enum for LDtkEnums
    /// </summary>
    public enum CameraSize
    {
        Tiny,
        Small,
        Medium,
        Large,
        ExtraLarge,
        ExtremelyLarge
    }

    /// <summary>
    /// LDtk Enum for LDtkEnums
    /// </summary>
    public enum EnemyType
    {
        Dummy,
        TaraBug,
        TaraCapBug,
        JumpBug
    }
}